{% set name = "pyrosar" %}
{% set version = "0.37.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f414d6ea40b4f3ae589ae3f7e8c72ef02a2e955ccd00ae5812c5a411a6d5c6ed

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.11
    - pip
    - setuptools
    - setuptools_scm
  run:
    - gdal >=2.4
    - geoalchemy2 >=0.14.0
    - libgdal
    - libspatialite >=5.1.0
    - lxml
    - numpy
    - packaging
    - pillow
    - progressbar2
    - psutil
    - psycopg2
    - python >=3.11
    - pyyaml
    - requests
    - spatialist >=0.17.0
    - sqlalchemy >=1.4
    - sqlalchemy-utils >=0.37,<0.42

test:
  imports:
    - pyroSAR
  commands:
    - pip check
  requires:
    - python >=3.11
    - pip

about:
  home: https://github.com/johntruckenbrodt/pyroSAR
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python Framework for Large-Scale SAR Satellite Data Processing

  description: |
    The pyroSAR package aims at providing a complete solution for the scalable organization and processing of SAR satellite data.
  doc_url: https://pyrosar.readthedocs.io
  dev_url: https://github.com/johntruckenbrodt/pyroSAR

extra:
  recipe-maintainers:
    - johntruckenbrodt
